# Generated by Django 6.0 on 2025-12-17 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "infrastructure",
            "0005_remove_campaign_tenant_remove_funnel_campaign_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="role",
            name="permissions",
            field=models.JSONField(default=list),
        ),
    ]
