# Generated by Django 6.0 on 2025-12-17 03:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("funnels", "0002_funnelexperiment_funnelevent_experiment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="funnelevent",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
