# Generated by Django 6.0 on 2025-12-16 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="opportunity",
            name="lead_score",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="opportunity",
            name="priority",
            field=models.CharField(default="Low", max_length=50),
        ),
    ]
