# Generated by Django 6.0 on 2025-12-18 01:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("funnels", "0003_lead_leadevent_leadstate"),
        ("infrastructure", "0006_alter_user_options_alter_user_managers_and_more"),
        ("sales", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="opportunity",
            name="owner",
        ),
        migrations.RemoveField(
            model_name="opportunity",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="opportunity",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="opportunities",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="opportunity",
            name="last_activity_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="opportunity",
            name="lead",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="opportunities",
                to="funnels.lead",
            ),
        ),
        migrations.AddField(
            model_name="opportunity",
            name="priority",
            field=models.CharField(
                choices=[("low", "Baja"), ("medium", "Media"), ("high", "Alta")],
                default="medium",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="opportunity",
            name="stage",
            field=models.CharField(
                choices=[
                    ("new", "Nuevo"),
                    ("contacted", "Contactado"),
                    ("proposal", "Propuesta Enviada"),
                    ("negotiation", "En Negociación"),
                    ("won", "Ganada"),
                    ("lost", "Perdida"),
                ],
                default="new",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Nuevo"),
                            ("in-progress", "En Progreso"),
                            ("resolved", "Resuelto"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                (
                    "sla_deadline",
                    models.DateTimeField(
                        help_text="Fecha y hora límite para la resolución (SLA)"
                    ),
                ),
                ("csat_score", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tickets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tickets",
                        to="funnels.lead",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tickets",
                        to="infrastructure.tenant",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="StageHistory",
        ),
    ]
